version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ETCD_ROOT_PASSWORD=1234
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd-data:/bitnami/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
volumes:
  etcd-data: